[package]
name = "faalsink"
version = "0.1.0"
edition = "2024"

[dependencies]
blake3 = "1.8.7"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["full"] }
walkdir = "2.5.0"
anyhow = "1.0.104"
lz4_flex = "0.14.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
tracing-appender = "0.2.5"
tempfile = "3.27.0"

